import * as esbuild from 'esbuild';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import { createRequire } from 'module';
import { execFileSync } from 'child_process';

const currentFile = fileURLToPath(import.meta.url);
const currentDir = path.dirname(currentFile);
const entryPoint = path.resolve(currentDir, 'src', 'components', 'index.ts');

const require = createRequire(import.meta.url);
const LocalizationGenerator = require('./scripts/localizationGenerator');

const localizationPlugin = {
  name: 'localization-plugin',
  setup(build) {
    build.onStart(async () => {
      try {
        const localizationGenerator = new LocalizationGenerator();
        localizationGenerator.generateLocalizationFile();
      } catch (error) {
        process.stderr.write(
          `Localization generation failed during build startup: ${error.message ?? error}\n`
        );
        throw error;
      }
    });
  },
};

// Every VALUE re-export in the public barrel becomes its own entry point.
//
// This is not cosmetic packaging. Thirteen modules call `createTheme` /
// `createBreakpoints` at module scope, and a bundler cannot prove those calls
// pure — bundled into one file they are top-level statements every importer has
// to retain, so pulling `UiButton` dragged every theme in the kit with it.
// (esbuild's `pure` does not help: it feeds esbuild's own DCE and emits no
// `@__PURE__` annotation for the consumer's bundler.) One entry per component
// puts each of those calls behind an import the consumer can simply not make.
//
// Derived from `index.ts` rather than from the directory listing, so the entry
// set and the public surface cannot drift: a component that is not exported is
// not published, and one that is gets its subpath automatically.
function componentEntryPoints() {
  const barrel = readFileSync(entryPoint, 'utf8');
  const directories = new Set();
  // `export { … } from './x'` only. `export type { … }` is erased at runtime and
  // needs no entry — its declarations ride the shared rollup.
  for (const match of barrel.matchAll(/^export \{[^}]*\} from '\.\/([^']+)'/gm)) {
    directories.add(match[1].split('/')[0]);
  }

  const entryPoints = { index: entryPoint };
  for (const directory of directories) {
    const base = path.resolve(currentDir, 'src', 'components', directory, 'index');
    const source = ['.tsx', '.ts'].map(extension => `${base}${extension}`).find(existsSync);
    if (source) {
      entryPoints[directory] = source;
    }
  }
  return entryPoints;
}

// The names the barrel re-exports from one component directory, split by whether
// they survive to runtime. Used to give each subpath a `.d.ts` whose shape
// matches its `.mjs` exactly.
function barrelNamesFor(barrel, directory) {
  const escaped = directory.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const from = `from '\\./${escaped}(?:/[^']+)?'`;
  const defaultAs = new RegExp(`export \\{ default as (\\w+) \\} ${from}`).exec(barrel);
  const values = [];
  const types = [];
  for (const match of barrel.matchAll(new RegExp(`export (type )?\\{([^}]*)\\} ${from}`, 'g'))) {
    for (const specifier of match[2].split(',')) {
      const name = specifier.trim();
      if (!name || name.startsWith('default as')) continue;
      (match[1] ? types : values).push(name);
    }
  }
  return { defaultExport: defaultAs ? defaultAs[1] : null, values, types };
}

// One `.d.ts` per subpath, re-exporting from the single API Extractor rollup.
// Types are erased, so a subpath importer pays nothing for the shared rollup —
// which keeps ONE self-contained declaration artifact (and the
// `ae-forgotten-export` gate that guards it) instead of running API Extractor
// once per entry.
function generateSubpathDeclarations(entryPoints) {
  const barrel = readFileSync(entryPoint, 'utf8');
  for (const directory of Object.keys(entryPoints)) {
    if (directory === 'index') continue;
    const { defaultExport, values, types } = barrelNamesFor(barrel, directory);
    const lines = [
      `// Generated by build.config.mjs — the '${directory}' subpath, typed from the rollup.`,
    ];
    if (defaultExport) lines.push(`export { ${defaultExport} as default } from './index';`);
    if (values.length) lines.push(`export { ${values.join(', ')} } from './index';`);
    if (types.length) lines.push(`export type { ${types.join(', ')} } from './index';`);
    writeFileSync(path.resolve(currentDir, 'build', `${directory}.d.ts`), `${lines.join('\n')}\n`);
  }
}

if (!existsSync(entryPoint)) {
  process.stdout.write(
    'Skipping build because this bootstrap PR does not include src/components/index.ts yet.\n'
  );
  process.exit(0);
}

async function generateTypeDeclarations() {
  // esbuild does not emit type declarations, so the library's published `.d.ts`
  // is produced in two steps: tsc emits per-file declarations (keeping the `@/*`
  // path aliases) under temp/dts, then API Extractor rolls them into a single
  // self-contained build/index.d.ts (resolving the aliases and inlining internals).
  //
  // tsc does not prune stale declarations for deleted/renamed sources, so a reused
  // temp/dts could feed API Extractor leftover files and make the rollup depend on
  // build history. Start from a clean intermediate directory for a deterministic result.
  const dtsOutDir = path.resolve(currentDir, 'temp', 'dts');
  rmSync(dtsOutDir, { recursive: true, force: true });

  const tscBin = require.resolve('typescript/bin/tsc');
  execFileSync(process.execPath, [tscBin, '-p', path.resolve(currentDir, 'tsconfig.dts.json')], {
    stdio: 'inherit',
    cwd: currentDir,
  });

  const { Extractor, ExtractorConfig } = await import('@microsoft/api-extractor');
  const extractorConfig = ExtractorConfig.loadFileAndPrepare(
    path.resolve(currentDir, 'api-extractor.json')
  );
  const result = Extractor.invoke(extractorConfig, {
    localBuild: true,
    showVerboseMessages: false,
  });
  if (!result.succeeded) {
    throw new Error(
      `API Extractor failed with ${result.errorCount} error(s) and ${result.warningCount} warning(s).`
    );
  }

  // Invariant: the rollup must be self-contained. Fail the build if any internal
  // `@/*` path-alias reference leaked through instead of being inlined — such a file
  // would not resolve for consumers of the published package. Covers every alias form
  // emitted into a `.d.ts`: `from "@/…"`, side-effect `import "@/…"`, and inline
  // dynamic-import types `import("@/…").Type`.
  const rollupPath = path.resolve(currentDir, 'build', 'index.d.ts');
  if (/(?:\bfrom\s+|\bimport\s*\(?\s*)['"]@\//.test(readFileSync(rollupPath, 'utf8'))) {
    throw new Error(
      'build/index.d.ts contains unresolved "@/..." path-alias imports; the API Extractor rollup did not inline them.'
    );
  }
}

esbuild
  .build({
    outdir: path.resolve(currentDir, 'build'),
    entryPoints: componentEntryPoints(),
    entryNames: '[name]',
    // Code shared by several entries is hoisted into `chunks/` instead of being
    // duplicated into each one. Requires `format: 'esm'`, which this build
    // already uses.
    splitting: true,
    chunkNames: 'chunks/[name]-[hash]',
    bundle: true,
    minify: true,
    format: 'esm',
    outExtension: { '.js': '.mjs' },
    // Externalize only peer dependencies — the consumer provides them. Swiper is
    // deliberately not a peer, so it and its carousel CSS must stay bundled
    // into build/index.css (exported as `@vilnacrm/ui-toolkit/styles.css`); blanket
    // `packages: 'external'` would drop those required styles from the library.
    external: [
      'react',
      'react-dom',
      'react/jsx-runtime',
      'react/jsx-dev-runtime',
      '@mui/*',
      '@emotion/*',
      'react-hook-form',
      'i18next',
      'react-i18next',
    ],
    tsconfig: path.resolve(currentDir, 'tsconfig.json'),
    sourcemap: true,
    target: ['es2020'],
    loader: {
      '.js': 'jsx',
      '.svg': 'dataurl',
      '.css': 'css',
      '.ttf': 'file',
    },
    resolveExtensions: ['.js', '.ts', '.jsx', '.tsx', '.json', '.svg'],
    plugins: [localizationPlugin],
    define: {
      'process.env.NODE_ENV': '"production"',
    },
  })
  .then(generateTypeDeclarations)
  .then(() => generateSubpathDeclarations(componentEntryPoints()))
  .catch(error => {
    process.stderr.write(`Build failed: ${error.message ?? error}\n`);
    process.exit(1);
  });
