services:
  bun:
    build: .
    restart: unless-stopped
  storybook:
    build: .
    command: ["sh", "-lc", "CI=1 bun x storybook dev --ci --host 0.0.0.0 -p 6006"]
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    environment:
      REACT_APP_STORYBOOK_URL: http://storybook:6006
    ipc: host
