import { Autocomplete } from '@mui/material';
import { render, screen } from '@testing-library/react';
import userEvent, { type UserEvent } from '@testing-library/user-event';
import React from 'react';

import { createFieldRenderInput } from '../../src/components/field-controls';

// The ghost-enabled fields (search/select/multi-select) always pass an `overlay` and
// input handlers, so they exercise the wrapped path. This covers the plain-field path:
// a config with no `overlay` and no `htmlInputProps` renders a bare field (no ghost
// wrapper) and composes MUI's own input handlers with the (absent) extras. Params are
// generated by a real MUI Autocomplete so they have the exact runtime shape.
describe('createFieldRenderInput — plain field (no overlay, no input handlers)', () => {
  it('renders a bare field and keeps MUI’s own input handlers', async () => {
    const user: UserEvent = userEvent.setup();
    render(
      <Autocomplete
        options={['A', 'B']}
        renderInput={createFieldRenderInput({ ariaLabel: 'City' })}
      />
    );
    const combobox: HTMLElement = screen.getByRole('combobox', { name: 'City' });
    expect(combobox).toBeInTheDocument();

    // MUI's own handlers must survive buildHtmlInput's merge: clicking opens the listbox
    // (input/focus wiring), and ArrowDown advances aria-activedescendant (composed
    // onKeyDown). A dropped handler leaves the popup shut or the highlight stuck.
    await user.click(combobox);
    const renderedOptions: HTMLElement[] = screen.getAllByRole('option');
    await user.keyboard('{ArrowDown}');
    expect(combobox).toHaveAttribute('aria-activedescendant', renderedOptions[0].id);
  });
});
