name: generate changelog and create pre release

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@469f0e5e35831fbd1962706f29f65daf0a5723f2 # v6.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'false'
          version-file: 'package.json'
          pre-release: 'true'
          git-push: 'false'
          skip-commit: 'true'
          skip-tag: 'true'
