name: bats testing

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  bats:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Bats shell coverage
        run: make test-bats BATS_FORMATTER=tap
