name: performance testing

on:
  pull_request:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  performance:
    name: lighthouse ${{ matrix.formFactor }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        formFactor: [desktop, mobile]
    env:
      CI: true
      INSTALL_CHROMIUM: 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Start docker test environment
        run: make start-bun

      - name: Run ${{ matrix.formFactor }} Lighthouse audit
        run: make lighthouse-${{ matrix.formFactor }}

      - name: Export the Lighthouse results
        if: always()
        run: make copy-lighthouse-reports

      - name: Upload the Lighthouse results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: lighthouse-${{ matrix.formFactor }}
          path: .lighthouseci/
          include-hidden-files: true
          retention-days: 30
          if-no-files-found: error

      - name: Stop docker test environment
        if: always()
        run: make down
